Traceback (most recent call last):
  File "C:\Users\marco\Alquimista\0-InTheOven\agentes_u\venv\lib\site-packages\botasaurus\browser_decorator.py", line 176, in run_task
    result = func(driver, data)
  File "C:\Users\marco\Alquimista\0-InTheOven\agentes_u\agente_leads\app.py", line 42, in scrape_place
    driver.get(link)
  File "C:\Users\marco\Alquimista\0-InTheOven\agentes_u\venv\lib\site-packages\botasaurus_driver\driver.py", line 628, in get
    self._tab = self._run(self._browser.get(link))
  File "C:\Users\marco\Alquimista\0-InTheOven\agentes_u\venv\lib\site-packages\botasaurus_driver\core\browser.py", line 257, in get
    frame_id, _, *_ = connection.send(cdp.page.navigate(url, referrer=referrer))
  File "C:\Users\marco\Alquimista\0-InTheOven\agentes_u\venv\lib\site-packages\botasaurus_driver\core\connection.py", line 248, in send
    result = parse_response(result, cdp_obj)
  File "C:\Users\marco\Alquimista\0-InTheOven\agentes_u\venv\lib\site-packages\botasaurus_driver\core\connection.py", line 45, in parse_response
    raise ChromeException(response["error"])
botasaurus_driver.exceptions.ChromeException: Invalid parameters [code: -32602]
